disableHttp: true
disableStashOutput: true

# 将默认用于覆盖订阅配置中的DNS配置
dns:
  enable: true
  ipv6: false
  listen: 0.0.0.0:53
  enhanced-mode: fake-ip
  fake-ip-range: 192.18.0.1/16
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 1.1.1.1
    - 114.114.114.114
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP

# Clash for Windows本身支持直接配置TUN模式，且大多数订阅不提供TUN配置
# 因此，默认情况下TUN配置不进行导入
tun:
  enable: true
  # 该模式需要添加防火墙规则（Add firewall rules）和安装服务模式（Service Mode）的支持
  stack: system # 默认为gvisor模式，但兼容性不好
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53