disableHttp: true
disableStashOutput: false

disableClashVergeOutput: false
configPathForClashVerge: C:\Users\dylan\.config\clash-verge\profiles
configNameForClashVerge: 
  - l1pZIstxfiBV
  - lOiKllfd4RWx
configRegexMatcher:
  - c9add9
  - SV8fXD

# 将默认用于覆盖订阅配置中的DNS配置
dns:
  enable: true
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 192.18.0.1/16
  nameserver:
    - 119.29.29.29
    - 223.5.5.5
  fallback:
    - 8.8.8.8
    - 1.1.1.1
    - 114.114.114.114
  fake-ip-filter:
    - +.stun.*.*
    - +.stun.*.*.*
    - +.stun.*.*.*.*
    - +.stun.*.*.*.*.*
    - "*.n.n.srv.nintendo.net"
    - +.stun.playstation.net
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - "*.msftncsi.com"
    - "*.msftconnecttest.com"
    - WORKGROUP

# Clash for Windows本身内置了TUN配置，因此大多数CFW的订阅也不提供TUN配置
# 但如果使用Clash Verge，则需要在订阅配置中添加TUN配置
tun:
  enable: true
  # 该模式需要添加防火墙规则（Add firewall rules）和安装服务模式（Service Mode）的支持
  stack: system # 默认为gvisor模式，但兼容性不好
  auto-route: true
  auto-detect-interface: true
  dns-hijack:
    - any:53